apiVersion: apis.kcp.dev/v1alpha1
kind: APIBinding
metadata:
  annotations: {}
  name: glbc
spec:
  permissionClaims:
  - group: ""
    resource: secrets
    state: "Accepted"
  - group: ""
    identityHash: DUMMY_HASH
    resource: services
    state: "Accepted"
  - group: apps
    identityHash: DUMMY_HASH
    resource: deployments
    state: "Accepted"
  - group: networking.k8s.io
    identityHash: DUMMY_HASH
    resource: ingresses
    state: "Accepted"
  reference:
    workspace:
      exportName: glbc
      path: root:kuadrant
