resources:
  - ../../kube-prometheus
  - ingress-prometheus.yaml
  - ingress-grafana.yaml
  - monitoring_resources/dashboard-glbc.yaml
  - monitoring_resources/dashboard-glbc-slo.yaml
  - monitoring_resources/rules-glbc-prometheusrule.yaml

# Patch grafana deployment to include dashboard configmaps
patchesJson6902:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: grafana
    path: grafana_patch.yaml
# Patch all PrometheusRules to be in the monitoring namespace
  - patch: |-
      - op: replace
        path: /metadata/namespace
        value: monitoring
    target:
      kind: PrometheusRule
      name: glbc-prometheus-rules
