apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kcp-glbc-controller-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kcp-glbc-controller-manager
subjects:
  - kind: ServiceAccount
    name: kcp-glbc-controller-manager
