blank_issues_enabled: false

contact_links:
  - name: Team Chat
    url: https://kuadrant.slack.com/archives/C03CV9Q48KA
    about: You can ask questions or discuss issues with the Hybrid Cloud team here.
