---
apiVersion: v1
kind: Secret
metadata:
  name: test.pb-custom.hcpapps.net
type: Opaque
data:
  ca.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUZDVENDQXZHZ0F3SUJBZ0lJVFdXQ0lRZjgvVkl3RFFZSktvWklodmNOQVFFTEJRQXdFekVSTUE4R0ExVUUKQ2hNSVMzVmhaSEpoYm5Rd0hoY05Nakl3T0RJek1UQTBNekk0V2hjTk1qTXdPREl6TVRBME16STRXakFUTVJFdwpEd1lEVlFRS0V3aExkV0ZrY21GdWREQ0NBaUl3RFFZSktvWklodmNOQVFFQkJRQURnZ0lQQURDQ0Fnb0NnZ0lCCkFMTllHSTBZTm1NVU84cUtZa3pjOXpibWxVT04rMk43Q2ZHd1NFVTQwTnJ2MWtXVWZyTGtSU20zQ3EvUDNyQUEKRGR6UE5yQ3JKZmNuajdZTi9KTEZZb2Q4S1JmZmhzdjU2RTZlOUp3dTNoVUhxSkFicFFCVGV5bkZjSUFtUzA4eAppNG0wMG1kam16WXZHRDlLUVdUeEEzLzcvNHBZUW9tMzFGQmxqYndEeXdFQVVYV0k3VUttQkUxY1dqYmg0cXc5CmxBL2IxSjlsTU9ESTZWRXpnYS9uZDJ0ZzNaRUJhY1pQQy9oUlg0d05lU0ZhNFA1QjhHVFNuUWVyNjJ3OU5SMmkKMlZmR25sVUprV1VQOTJUMFlTOVdSSktQUmEwYnVuSzVwYk94VllFV3FJU3o0SWYyenhlV2tFZE40NFA2TFI0cgpUR2RlSTc1ZTg2b3BvYjVxNUREOXQ2ajRTY2RFN2VWalJvSWRTU2Q2TzNBc1hHeGZ3cEdZeTN2NlZVdW12alBtCjE5VmpETENsZkhZYzNHVXovWFpFOFh2aXlJQmYyc0w1QXJDVkU5aVQrQ2hDNzllYm5iLzQ3WjMwMi8xZlNla24KT0NocGt2UHRYTE9EZ0s1VnhOTWVxKzFOcldLdGdWR3pFbVI4ZXZpSEN0eGtzajUzeC9OSWY3ZzZZM0JQOXN5Ugp3NmpZbHF3TFc1NFdWR2xUTnVVdG1qbnU2a3NidXJyL0dLemNxOUsxb09oN3pySHF0eEFkQVNrbWxlVUE5MG5ZClRkK1A0eFFDa3hFdzZrSmFRYWp2NGlqdVdQK2ttU1ZCWVBxMkVjNUFaa3R1SFFkNnltWExtZmY2SmJoQjM1WjUKZFRHZTlqOUd6UXJvbTEwQzlGMnBFNHVCNytnVDBqaGg0eG1VbERwUUNqclRBZ01CQUFHallUQmZNQTRHQTFVZApEd0VCL3dRRUF3SUNoREFkQmdOVkhTVUVGakFVQmdnckJnRUZCUWNEQWdZSUt3WUJCUVVIQXdFd0R3WURWUjBUCkFRSC9CQVV3QXdFQi96QWRCZ05WSFE0RUZnUVVMZnkwYWJlanI5Uk1nMHY0V1luV1ZBRU5wd2t3RFFZSktvWkkKaHZjTkFRRUxCUUFEZ2dJQkFId091d0RQN1hxN1ZrczZ4Mk9SLzJNbXJJc0xhRCtIbkhSN20rNjdKL21VZXBGcwoyNVo3c09uZUVXV0ZMSW44Mk1RTTFxSkhTc2lIN3IvYlJQOFBTdEJvNW5HTzJHcHV6dHBRWHBnRUl5RWd5b2twCjFxcWY2czk1NUZFb2tnV3dsMWZWY2w1cEZyLzhWa25BQXBOWkdXTWNwckFicUo4eUJLbXpJUkw0SE1aZnd5MVQKZTNtQno3VndBUkpSc2tqT3RkK3NjaTY1M2JHZjE1ak9zM0VsSnFIeS9nRU5vbTlrQXVmckZEQmREWlpQNHJmdgpydmtHYWpOMFZRU21tbkp2NXl0UXMrakw1eGkxODdZOVZkdFlPMVVDMVJJRjNkOXUyaUZkZVNOOFpFRTR3Y1U2CnRHaEpSWGpoS2I5REdGYWVHWjkwaDVLSjZUQ3dCVzBTU01qbXZ2dkpMSW1POXdXVEltU1BwbXg2RDJhd3lFZkcKc1JWOE5OKzYrNEplUHdnQ0hnS1VCRWtPbDRZU2RKR0Jsdm11YlFVQlV2V1E5Y1ViNFlKRXZUV043a1QwQ0JjcQpuV3NqL253eWx3U2JjRFUzMTNEc2czNmxvakY1QXE4ZXhnbUZDanE4NjNzaytuOWx2MllRdGZ6eUh6WG9PVG1ICnYvK29NNGZKdW1qZTV1NWRuNDFENmw2M2UzeGpnTXQvUWYzZ2lZcVdRUDY3S3lRRUUvUnJFa1I5MlFrZFhveFkKQ1ZjMlVNY2dTSWYvaUVDNG1aWndwTTQrS3VMNTJEMFg4WnkycGtTZjF6YUpxaGRRVXpoUm02Qy9wRUpDOVpXZApPaGR3RThSWEtRdTgyNy83UkZnUEpDbWZpOHkvU2lFL1RYVURSazU5U1c0OGFmNUFNbXBDWmp4ODhnWFoKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVBVENDQWVtZ0F3SUJBZ0lRT1F5clh6TURYd0NIOGZpNU12eUxMakFOQmdrcWhraUc5dzBCQVFzRkFEQVQKTVJFd0R3WURWUVFLRXdoTGRXRmtjbUZ1ZERBZUZ3MHlNakE0TWpNeE1UQXdNalphRncweU1qRXhNakV4TVRBdwpNalphTUFBd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUJEd0F3Z2dFS0FvSUJBUURFV3VQM1FSV0cwdWJUClpob0l2RkpPRE15VC9QQXliSTJPZUFQbzRSeUlIbW5WRkh4TkxqaXIrVTI3QW1YaWNFcGFOdVA3Y1FLdWdOSSsKc0tJVy9qRGlHN1FkZXR1UWJidEJnM1N3TGJqR2ZseFFMZHozb2ZpZ3NnV1phZnJ3OGl3Znh5UzRXcGNJTVBCNgo3N1htclJyUDY0MjJKOERtY2JtOW1oaUpEM1E2bWRMa3hTREFyNDU0WlM2RGdqL3BkK1NBQld4a1BJUjNzMlc3CkJxei9kQUlxcnFKL01SZ0M4SDI3MnlCUXZZeWVvakZRTklNMGpzc3VRK3dqQ1pqWXRsQ211QjBXY1d4QXdQK1YKenpHL0NqVG5NVUFlNUtMMFZGM0t5S1VXcjFVYWlMMndQM3RxV1VVT3AwM2I2KzhMYkREaVloc255QnNMTFJEVApVRjhXRStHUkFnTUJBQUdqWkRCaU1BNEdBMVVkRHdFQi93UUVBd0lGb0RBTUJnTlZIUk1CQWY4RUFqQUFNQjhHCkExVWRJd1FZTUJhQUZDMzh0R20zbzYvVVRJTkwrRm1KMWxRQkRhY0pNQ0VHQTFVZEVRRUIvd1FYTUJXQ0UzUmwKYzNRdWNHSXVhR053WVhCd2N5NXVaWFF3RFFZSktvWklodmNOQVFFTEJRQURnZ0lCQUhnblFRTVFveDB2MFY2ZApTVERkcmN2UmgwVDFnSDR0NVJYZEZXQ0RyZDF2RTZoTkR2NkMrQS9WY1dPRjdLWDhWTFIyNU9FY3BtUTIzR1lOCmlWRnlwWkhOSjQ4Mjlnb0lYcXMzOXpNYjdOTElrUHM1MWtndC9nbmg3V1B2d0U1aHRzU2VxYjZ2di9rcGJYbngKVU1RbC9zdjg1alVocC8ydVdPT0ZBR0ttdWRJZ2czbUZzenR2ZFpkK3N5UHFJVUdWd1ZIZVg4Y0o5cFcvOTZSZAptUVk2V2NNU2tLbFMwUkZVaFJGUUdSMEh3RmZQUGMyeStMZ0ZIQnB2aGc4S25xbnVaekFVTFJhOHR2RnF2bktDCkdxMHA2LzFNSUhZZjZhK0lGbTA3UVUrUDB2TlJVVEZ3NXdDQllEckpNTW16NStvR1JwTUp2dzVTbVZXMW44WC8Kb1orUHIyU0cxR0Q1UFFnamJraFcxODk1U0orSTlOWUNlb2t5Q2xRRE1jRDZ5YmUxUE9YRDJTSHExZkVaYnRXdAorbmp5ZGQ0Tm5nZlBzQVhNeW9Oa04zd1VTdDhzRUR2U25KUm5CeWhVUldsRjJXUTlHTHlQVkVvcVdnS3FYU3ZYCi9HZVRBVmFqY2dacVRicWhSWUhoWG1sNHFBOVliRzRYTXloOTVrWGhqSTA4bnJ0dWdZd1Ftb05qWUFuRzlqV0MKVVpZS2tjMWhwdldkRXVaRWRpMHBBT05HMHdoVWxvTXNKb2laVzJiQUwwenFKNFBDcE5waEF0M3N5U0d0endnbApWNG90a2xzY0ZRNVlqQnUvRG1FY0FoMUtMZE1VQmV5ZEN5dTVmOWRwcFREcFRid3l1K0pZbHpkRkpSUXF1R2RxCk9maTk3WkdHUG9nWFRUdzdTT0JINjhMN2FZUXcKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
  tls.key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcEFJQkFBS0NBUUVBeEZyajkwRVZodExtMDJZYUNMeFNUZ3pNay96d01teU5qbmdENk9FY2lCNXAxUlI4ClRTNDRxL2xOdXdKbDRuQktXamJqKzNFQ3JvRFNQckNpRnY0dzRodTBIWHJia0cyN1FZTjBzQzI0eG41Y1VDM2MKOTZING9MSUZtV242OFBJc0g4Y2t1RnFYQ0REd2V1KzE1cTBheit1TnRpZkE1bkc1dlpvWWlROTBPcG5TNU1VZwp3SytPZUdVdWc0SS82WGZrZ0FWc1pEeUVkN05sdXdhcy8zUUNLcTZpZnpFWUF2Qjl1OXNnVUwyTW5xSXhVRFNECk5JN0xMa1BzSXdtWTJMWlFwcmdkRm5Gc1FNRC9sYzh4dndvMDV6RkFIdVNpOUZSZHlzaWxGcTlWR29pOXNEOTcKYWxsRkRxZE4yK3Z2QzJ3dzRtSWJKOGdiQ3kwUTAxQmZGaFBoa1FJREFRQUJBb0lCQUREOGMrOFZmNmRaS2xrSApHZXVmLy9DVTVOenV0NFg4NnZ2bUdTT2FOYUlINUdOU2J3aGFSYTB4enlDZW9vaHhkenMyZ240U1haYm5jSXhQClNNRHZ2WVpMWHc0VHZuOHp3UW5CSC9Wc0VyTUNoMGxCaCtVSHRaMXhqRkFQenBrWjhjUWp6SmRwa2xCcTFUUDIKWmEwYzlwbDByTEFMRHVidTdHWE84ZHdQelBGcFN2SGdueHV2bnErVkx3T3JCYVhZZytYUWVLMGxHamVGYWJBVgpESnhsSXd5TEhYaG9vRlpwTTZhanByeHJvUWtmL25HVmwvenFTRzl4SVF1VVdYc3JXV2xnVGtoZ01wSHFUS29xCnR1TGszdmEyU1cvb0plL3dKUFBzOGtHV1pYZHJXa1dTQlg1L2lJb0tMVTNBbzcyZWlzamgxQlVEZXBxeTRmdkEKSXdSZ3VSa0NnWUVBMkhvWmExcXJaSkJhVkM3WGFNWHNkaXh3M2YzWDJ5S0QyVVRNU2hncEQvYnJyUDBDZmtmQQpNUElSSFlGalpXSmxSamNnczVRclF3bDJ0bUNuRHVKd3lNMUtvRXdTNWFya3JrbURIZDBEaXVPRVF1bkNUOUpTCmpjYWZtOWhkcld0YzlsN0U1RzJYNEtkbFVCMm41RnJMYzUyaUF4VG80US9kQ2JZVWhOeEdKK3NDZ1lFQTZEUlEKa1FsNEZnQ29jNnE0YVJXYlg5S09pVDB2cDduV2dGSE1GWWhwaks4YjFLcWp0UFdCSDNwYW1oOXpQcjIxbE96OApQTkJiN3JSak80S2JFOEZtSHRhOU1IOGNuOHJNOXRKZHlSUGFHdWxSL0VQYnprc1hUOS9PSURoajVTaVEvbE1DCk9zbXlLQ2oyQ0FRQlVVVVdlak5zYjhZWU1jWTk0cjloZ3lsK0dYTUNnWUFHeHl2c2xKWXhPK1BZSnU5UHRJTEcKNEhWWVBnNTRLZ2grMFF5a2RVVXozc05hVTBHMHVvSm1CZTVMUWpYZWdzb3cvS0RsZm9vc095dWdZajVZMVBZNwpFMUoyMm1ydERnRERCRUk2dVNUWFFIQnZ0K29CbmRBLzZDd3ZNUU1kM3ZLMk5CbHVIWkJYMUdYenNEb0ZpR0krCmFIMGVJNVYzRm93Uk5jWkdzcTd2cVFLQmdRREsreGhHZ05tSm1rK210T0Q1YzFyY0c4cGZxNjNoMTdEcmdSVisKNlQwakx0dU1QeEpXR0pva015ZktQSjNZaGF1YW9NTXFRaFZyQ0NNS25YUUVnL1pLRlB0U3pucnVNRENWdm5VZgpWZ3c5cENIMy9EWEVFcDR4UTNvRGJtZmNwV2FCKzN3aWViZ1VKU0pWQlhORllMaHlZRXQxTmR4bWZsNFF2YTEzCkk2bElnd0tCZ1FDSGRNM3hWTEFlQzRCdHlnMXpQTkJmRUlNWjM2bVVpaDVDcU5paEE5dkpoVFdJeStHcHlmd2cKQ2JNVlcwdDNnTmQvYlRCWGpQN01ZMTJsNnBUWVNUMDRtaHpyVktRMFdTNUp6VWVaY1VhOHRrVGZNMHJ3LzlmWAplQVl3RjZMc2xvbjJkSWpkd1ZLUTQ5eHEydDdDUCtDT0lrTXJTcWdka29Bc212d2wxQjN1VVE9PQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=
---
apiVersion: kuadrant.dev/v1
kind: DomainVerification
metadata:
  name: pb-custom.hcpapps.net
spec:
  domain: pb-custom.hcpapps.net
---
apiVersion: v1
kind: Service
metadata:
  name: httpecho-both
spec:
  ports:
    - name: http-port
      port: 80
      targetPort: http-port
      protocol: TCP
  selector:
    app: echo-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echo-server
  template:
    metadata:
      labels:
        app: echo-server
    spec:
      containers:
        - name: echo-server
          image: jmalloc/echo-server
          ports:
            - name: http-port
              containerPort: 8080
              protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-custom-domain
spec:
  tls:
    - hosts:
      - test.pb-custom.hcpapps.net
      secretName: test.pb-custom.hcpapps.net
  rules:
    - host: test.pb-custom.hcpapps.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: httpecho-both
                port:
                  number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-no-domain
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: httpecho-both
                port:
                  number: 80
