apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: argocd
spec:
  description: argocd app project
  sourceRepos:
    - git@github.com:redhat-cps/glbc-deployments.git
  clusterResourceWhitelist:
    - group: 'apiextensions.k8s.io'
      kind: 'CustomResourceDefinition'
    - group: 'rbac.authorization.k8s.io'
      kind: 'ClusterRole'
    - group: 'rbac.authorization.k8s.io'
      kind: 'ClusterRoleBinding'
    - group: ''
      kind: 'Namespace'
  destinations:
  - namespace: argocd
    name: in-cluster