apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: istiocontrolplane
spec:
  profile: default
  namespace: istio-system
  components:
    base:
      enabled: true
      k8s:
        securityContext:
          runAsUser: ""
          fsGroup: ""
          runAsGroup: ""
    cni:
      enabled: false
    egressGateways:
      - enabled: false
        name: istio-egressgateway
    ingressGateways:
      - enabled: true
        name: istio-ingressgateway
        k8s:
          securityContext:
            runAsUser: ""
            fsGroup: ""
            runAsGroup: ""
    pilot:
      enabled: true
      k8s:
        securityContext:
          runAsUser: ""
          fsGroup: ""
          runAsGroup: ""
        env:
          - name: ENABLE_LEGACY_FSGROUP_INJECTION
            value: "false"
  values:
    pilot:
      autoscaleEnabled: false
    gateways:
      istio-ingressgateway:
        type: NodePort
        autoscaleEnabled: false
    global:
      istioNamespace: istio-system