rule_files:
  - ../rules-glbc.yaml

evaluation_interval: 1m

tests:
  - interval: 1m
    input_series:
      # 0m - 5m container is up
      # 5m - 20m container is down
      - series: up{container="manager",job="observability-operator/podmonitor-kcp-glbc-controller-manager"}
        values: "1+0x5 0+0x15"
    alert_rule_test:
      - eval_time: 5m
        alertname: GLBCTargetDown
        exp_alerts: []
      - eval_time: 20m
        alertname: GLBCTargetDown
        exp_alerts:
          - exp_labels:
              severity: critical
              container: manager
              job: observability-operator/podmonitor-kcp-glbc-controller-manager
            exp_annotations:
              summary: 'GLBC Prometheus Target is down'
              description: 'The GLBC Prometheus Target is down. Either the GLBC component is not running, is misconfigured, or the metrics endpoint is not responding.'
              runbook_url: 'https://github.com/Kuadrant/kcp-glbc/blob/main/docs/observability/runbooks/glbctargetdown.adoc'

  - interval: 1m
    input_series:
      # 0m - 5m container is up
      # 5m - 20m no time series exists
      - series: up{container="manager",job="observability-operator/podmonitor-kcp-glbc-controller-manager"}
        values: "1+0x5 stale"
    alert_rule_test:
      - eval_time: 5m
        alertname: GLBCTargetDown
        exp_alerts: []
      - eval_time: 20m
        alertname: GLBCTargetDown
        exp_alerts:
          - exp_labels:
              severity: critical
              container: manager
            exp_annotations:
              summary: 'GLBC Prometheus Target is down'
              description: 'The GLBC Prometheus Target is down. Either the GLBC component is not running, is misconfigured, or the metrics endpoint is not responding.'
              runbook_url: 'https://github.com/Kuadrant/kcp-glbc/blob/main/docs/observability/runbooks/glbctargetdown.adoc'
