rule_files:
  - ../rules-glbc.yaml

evaluation_interval: 1m

tests:
  - interval: 1m
    input_series:
      - series: glbc_aws_route53_request_errors_total{pod="glbc"}
        values: "0+0x60 2+2x65"
      - series: glbc_aws_route53_request_total{pod="glbc"}
        values: "100+100x125"
    alert_rule_test:
      - eval_time: 60m
        alertname: HighDNSProviderErrorRate
        exp_alerts: []
      - eval_time: 125m
        alertname: HighDNSProviderErrorRate
        exp_alerts:
          - exp_labels:
              severity: warning
              pod: glbc
            exp_annotations:
              summary: 'High DNS Provider Error Rate'
              description: 'Excessive errors - The error rate is 0.02, which is greater than the threshold which is 1%'
              runbook_url: 'https://github.com/Kuadrant/kcp-glbc/blob/main/docs/observability/runbooks/HighDNSProviderErrorRate.adoc'