apiVersion: apis.kcp.dev/v1alpha1
kind: APIBinding
metadata:
  annotations: {}
  name: glbc
spec:
  acceptedPermissionClaims:
  - group: ""
    resource: secrets
  - group: ""
    identityHash: f3803ca5e0b056d8cd27ae2b2c3d949d8e5f08da37b682de2ee9974855093caa
    resource: services
  - group: apps
    identityHash: f3803ca5e0b056d8cd27ae2b2c3d949d8e5f08da37b682de2ee9974855093caa
    resource: deployments
  - group: networking.k8s.io
    identityHash: f3803ca5e0b056d8cd27ae2b2c3d949d8e5f08da37b682de2ee9974855093caa
    resource: ingresses
  reference:
    workspace:
      exportName: glbc-root-kuadrant
      path: root:kuadrant
