name: CI

on:
  push:
    branches:
      - main
      - 'release-*'
    paths-ignore:
      - '**.adoc'
      - '**.md'
      - 'samples/**'
      - 'LICENSE'
  pull_request:
    branches:
      - main
      - 'release-*'
    paths-ignore:
      - '**.adoc'
      - '**.md'
      - 'samples/**'
      - 'LICENSE'

jobs:

  lint:
    name: lint
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: v1.17
      - uses: golangci/golangci-lint-action@v2
        with:
          version: v1.44.2
          only-new-issues: true
          args: --timeout=5m
          skip-go-installation: true

  codegen:
    name: codegen
    strategy:
      matrix:
        platform: [ ubuntu-20.04, macos-11 ]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: v1.18
      - name: Check generate
        run: make verify-generate
      - name: Check monitoring resources generate
        run: make verify-gen-monitoring-resources

  test:
    name: test
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: v1.18
      - run: make build
      - run: PATH="${PATH}:$(pwd)/bin/" make test
      - run: make prometheus-rules-unit-test
